name: Build Check
on: [pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Java
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '19'
        distribution: 'oracle'
        cache: 'maven'

    - name: Run Build
      run: mvn clean package
